# Package building stuff - Experimental!
SET(CPACK_PACKAGE_VERSION "${SBPL_VERSION}")
SET(CPACK_PACKAGE_VERSION_MAJOR "${SBPL_MAJOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_MINOR "${SBPL_MINOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_PATCH "${SBPL_PATCH_VERSION}")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${V_MAJOR}.${V_MINOR}")
SET(CPACK_PACKAGE_CONTACT "Maxim Likhachev/maximl@seas.upenn.edu")
SET(CPACK_PACKAGE_VENDOR "University of Pennsylvania")
SET(CPACK_GENERATOR "DEB")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME
  "${PROJECT_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")

 # This must always be last statement!
INCLUDE(CPack)

